/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author sos
 */
public class JDialogAddScript extends javax.swing.JDialog {

    public boolean bSuccess;
    public Script scr;
    /**
     * Creates new form JDialogAddScript
     * @param parent
     * @param modal
     */
    public JDialogAddScript(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bSuccess = false;
        scr = new Script();
    }

    public JDialogAddScript(java.awt.Frame parent, boolean modal, Script inScr) {
        super(parent, modal);
        initComponents();
        bSuccess = false;

        if (inScr != null) {
            scr = inScr;
            jTextFilename.setText(scr.getName());
            jTextScript.setText(scr.getContent());
            switch(scr.getType()) {
                case "DDL":
                    jRadioButtonDDL.setSelected(true);
                    break;
                case "DML":
                    jRadioButtonDML.setSelected(true);
                    break;
                default:
                    jRadioButtonOther.setSelected(true);
            }
            jTextObjectName.setText(scr.getDBObjectName());
        }
    }

    void DeriveFilename()
    {
        String s;

        s = jTextObjectName.getText();

        if (jRadioButtonDDL.isSelected())
            s += ".DDL";
        else
            if (jRadioButtonDML.isSelected())
                s += ".DML";

        s += ".sql";
        
        jTextFilename.setText(s);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupScriptType = new javax.swing.ButtonGroup();
        buttonGroupSingleMulti = new javax.swing.ButtonGroup();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jRadioButtonDML = new javax.swing.JRadioButton();
        jRadioButtonDDL = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSingle = new javax.swing.JRadioButton();
        jRadioButtonMulti = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextScript = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextObjectName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFilename = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add script");

        buttonGroupScriptType.add(jRadioButtonOther);
        jRadioButtonOther.setSelected(true);
        jRadioButtonOther.setText("Other");
        jRadioButtonOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtherActionPerformed(evt);
            }
        });

        buttonGroupScriptType.add(jRadioButtonDML);
        jRadioButtonDML.setText("DML");
        jRadioButtonDML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDMLActionPerformed(evt);
            }
        });

        buttonGroupScriptType.add(jRadioButtonDDL);
        jRadioButtonDDL.setText("DDL");
        jRadioButtonDDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDDLActionPerformed(evt);
            }
        });

        jLabel1.setText("Script type:");

        buttonGroupSingleMulti.add(jRadioButtonSingle);
        jRadioButtonSingle.setSelected(true);
        jRadioButtonSingle.setText("Single");

        buttonGroupSingleMulti.add(jRadioButtonMulti);
        jRadioButtonMulti.setText("Multi");

        jLabel2.setText("Object count:");

        jLabel3.setText("Object type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Table", "View", "Package", "Type", "Mixed" }));

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextScript.setColumns(20);
        jTextScript.setRows(5);
        jTextScript.setToolTipText("Paste your code here");
        jScrollPane1.setViewportView(jTextScript);

        jLabel4.setText("Object name:");

        jTextObjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextObjectNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Filename");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonOther)
                                    .addComponent(jRadioButtonSingle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonDML)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonDDL))
                                    .addComponent(jRadioButtonMulti))
                                .addGap(0, 94, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextObjectName))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFilename))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDML)
                    .addComponent(jRadioButtonDDL)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSingle)
                    .addComponent(jRadioButtonMulti)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDMLActionPerformed
        scr.setType("DML");
        DeriveFilename();
    }//GEN-LAST:event_jRadioButtonDMLActionPerformed

    private void jRadioButtonDDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDDLActionPerformed
        scr.setType("DDL");
        DeriveFilename();
    }//GEN-LAST:event_jRadioButtonDDLActionPerformed

    private void jTextObjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextObjectNameActionPerformed
        DeriveFilename();
    }//GEN-LAST:event_jTextObjectNameActionPerformed

    // OK
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        bSuccess = true;
        scr.setName(jTextFilename.getText());
        scr.setContent(jTextScript.getText());
        scr.setDBObjectName(jTextObjectName.getText());
        dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed
    // CANCEL
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        bSuccess = false;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jRadioButtonOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtherActionPerformed
        scr.setType("");
        DeriveFilename();
    }//GEN-LAST:event_jRadioButtonOtherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAddScript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAddScript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAddScript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAddScript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAddScript dialog = new JDialogAddScript(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupScriptType;
    private javax.swing.ButtonGroup buttonGroupSingleMulti;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonDDL;
    private javax.swing.JRadioButton jRadioButtonDML;
    private javax.swing.JRadioButton jRadioButtonMulti;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JRadioButton jRadioButtonSingle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFilename;
    private javax.swing.JTextField jTextObjectName;
    private javax.swing.JTextArea jTextScript;
    // End of variables declaration//GEN-END:variables
}
